version: "3.9"
services:

    web-ui:
        image: "ashpazbashibackofficeapi:1"
        ports:
            - "8002:80"
        depends_on:
            - web-api
            
    web-api:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
            
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
  